[package]
name = "teawiebot"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/getchoo/teawieBot"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bottomify = "1.2.0"
dotenvy = "0.15.7"
env_logger = "0.10.0"
include_dir = "0.7.3"
log = "0.4.20"
poise = "0.5.7"
once_cell = "1.18.0"
rand = "0.8.5"
reqwest = { version = "0.11.22", default-features = false, features = [
	"rustls-tls",
	"json",
] }
serde = "1.0.192"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
url = { version = "2.4.1", features = ["serde"] }
