[package]
name = "teawiebot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bottomify = "1.2.0"
include_dir = "0.7.3"
once_cell = "1.18.0"
rand = "0.8.5"
regex = "1.9.3"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls", "json"] }
serde = "1.0.185"
serenity = "0.11.6"
tokio = { version = "1.31.0", features = ["macros", "rt-multi-thread"] }
