[package]
name = "teawiebot"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/getchoo/teawieBot"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bottomify = "1.2.0"
color-eyre = "0.6.2"
dotenvy = "0.15.7"
env_logger = "0.10.0"
include_dir = "0.7.3"
log = "0.4.20"
poise = "0.5.7"
once_cell = "1.18.0"
rand = "0.8.5"
redis = { version = "0.23.3", features = ["tokio-comp", "tokio-rustls-comp"] }
redis-macros = "0.2.1"
reqwest = { version = "0.11.22", default-features = false, features = [
	"rustls-tls",
	"json",
] }
serde = "1.0.193"
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = [
	"macros",
	"rt-multi-thread",
	"signal",
] }
url = { version = "2.5.0", features = ["serde"] }
