name: audit crates
# this checks our dependencies for
# security advisories every saturday

on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: run audit
        run: |
          nix build --accept-flake-config -L .#checks.x86_64-linux.audit
