name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.nix"
      - "**.rs"
      - "**.lock"
      - "Cargo.toml"
  pull_request:
    paths:
      - "**.nix"
      - "**.rs"
      - "**.lock"
      - "Cargo.toml"
  workflow_dispatch:

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run build
        run: |
          cargo build --locked --release

  nix:
    name: Nix

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run flake checks
        run: |
          nix flake check \
            --all-systems \
            --print-build-logs \
            --show-trace

  release-gate:
    name: CI Release gate
    needs: [build, nix]

    runs-on: ubuntu-latest

    steps:
      - name: Exit with error
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
