name: update nix flake
# this is to make sure we can build against a
# recent version of nixos-unstable

on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22

      - uses: DeterminateSystems/update-flake-lock@v19
        with:
          commit-msg: "deps(flake): update inputs"
          pr-title: "deps(flake): update inputs"
